"""empty message

Revision ID: 016dd2d3f774
Revises: 04bbbaaff277
Create Date: 2016-06-27 19:45:39.268266

"""

# revision identifiers, used by Alembic.
revision = '016dd2d3f774'
down_revision = '04bbbaaff277'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('create_on', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True))
    op.create_index(op.f('ix_application_create_on'), 'application', ['create_on'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_create_on'), table_name='application')
    op.drop_column('application', 'create_on')
    ### end Alembic commands ###
