"""empty message

Revision ID: 04bbbaaff277
Revises: 9f9dff127b37
Create Date: 2016-06-27 19:22:41.963528

"""

# revision identifiers, used by Alembic.
revision = '04bbbaaff277'
down_revision = '9f9dff127b37'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('host', sa.String(length=128), nullable=True))
    op.add_column('application', sa.Column('image', sa.String(length=256), nullable=True))
    op.add_column('application', sa.Column('verify', sa.String(length=256), nullable=False))
    op.create_index(op.f('ix_application_appname'), 'application', ['appname'], unique=False)
    op.create_index(op.f('ix_application_containerId'), 'application', ['containerId'], unique=False)
    op.create_index(op.f('ix_application_image'), 'application', ['image'], unique=False)
    op.create_index(op.f('ix_application_verify'), 'application', ['verify'], unique=False)
    op.drop_index('ix_application_create_on', table_name='application')
    op.drop_constraint(u'application_ibfk_1', 'application', type_='foreignkey')
    op.drop_column('application', 'project_id')
    op.drop_column('application', 'create_on')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('create_on', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('application', sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'application_ibfk_1', 'application', 'project', ['project_id'], ['id'])
    op.create_index('ix_application_create_on', 'application', ['create_on'], unique=False)
    op.drop_index(op.f('ix_application_verify'), table_name='application')
    op.drop_index(op.f('ix_application_image'), table_name='application')
    op.drop_index(op.f('ix_application_containerId'), table_name='application')
    op.drop_index(op.f('ix_application_appname'), table_name='application')
    op.drop_column('application', 'verify')
    op.drop_column('application', 'image')
    op.drop_column('application', 'host')
    ### end Alembic commands ###
