"""empty message

Revision ID: 0a105b34fb10
Revises: 30a604189929
Create Date: 2016-06-26 22:37:05.647981

"""

# revision identifiers, used by Alembic.
revision = '0a105b34fb10'
down_revision = '30a604189929'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('success', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'success')
    ### end Alembic commands ###
