"""empty message

Revision ID: 29434873e3d5
Revises: 504c2c6e3ef7
Create Date: 2016-06-26 22:44:05.863358

"""

# revision identifiers, used by Alembic.
revision = '29434873e3d5'
down_revision = '504c2c6e3ef7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('success', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'success')
    ### end Alembic commands ###
