"""empty message

Revision ID: 30a604189929
Revises: 77e9dd7abcba
Create Date: 2016-06-22 10:06:51.784482

"""

# revision identifiers, used by Alembic.
revision = '30a604189929'
down_revision = '77e9dd7abcba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('build', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'build')
    ### end Alembic commands ###
