"""empty message

Revision ID: 3b59ce42c47b
Revises: 29434873e3d5
Create Date: 2016-06-27 14:34:20.433627

"""

# revision identifiers, used by Alembic.
revision = '3b59ce42c47b'
down_revision = '29434873e3d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appname', sa.String(length=256), nullable=False),
    sa.Column('port', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_server',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('app_id', 'server_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_server')
    op.drop_table('application')
    ### end Alembic commands ###
