"""empty message

Revision ID: 47809939c22e
Revises: b5a8040dd658
Create Date: 2016-06-14 14:11:16.679229

"""

# revision identifiers, used by Alembic.
revision = '47809939c22e'
down_revision = 'b5a8040dd658'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github_token', sa.String(length=526), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'github_token')
    ### end Alembic commands ###
