"""empty message

Revision ID: 504c2c6e3ef7
Revises: 0a105b34fb10
Create Date: 2016-06-26 22:43:53.935740

"""

# revision identifiers, used by Alembic.
revision = '504c2c6e3ef7'
down_revision = '0a105b34fb10'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'success')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('success', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    ### end Alembic commands ###
