"""empty message

Revision ID: 63e6b0fbe576
Revises: 016dd2d3f774
Create Date: 2016-07-05 15:10:39.628166

"""

# revision identifiers, used by Alembic.
revision = '63e6b0fbe576'
down_revision = '016dd2d3f774'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_server')
    op.add_column('project', sa.Column('tag', sa.String(length=64), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'tag')
    op.create_table('app_server',
    sa.Column('app_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('server_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], [u'application.id'], name=u'app_server_ibfk_1'),
    sa.ForeignKeyConstraint(['server_id'], [u'server.id'], name=u'app_server_ibfk_2'),
    sa.PrimaryKeyConstraint('app_id', 'server_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
