"""empty message

Revision ID: 77090ff1acad
Revises: None
Create Date: 2016-07-13 15:00:12.921544

"""

# revision identifiers, used by Alembic.
revision = '77090ff1acad'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_role_default'), 'role', ['default'], unique=False)
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=256), nullable=False),
    sa.Column('Ip', sa.String(length=64), nullable=False),
    sa.Column('create_on', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_Ip'), 'server', ['Ip'], unique=False)
    op.create_index(op.f('ix_server_create_on'), 'server', ['create_on'], unique=False)
    op.create_index(op.f('ix_server_nickname'), 'server', ['nickname'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('github_token', sa.String(length=256), nullable=True),
    sa.Column('gitlab_token', sa.String(length=256), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_application_appname'), 'application', ['appname'], unique=False)
    op.create_index(op.f('ix_application_containerId'), 'application', ['containerId'], unique=False)
    op.create_index(op.f('ix_application_create_on'), 'application', ['create_on'], unique=False)
    op.create_index(op.f('ix_application_image'), 'application', ['image'], unique=False)
    op.create_index(op.f('ix_application_verify'), 'application', ['verify'], unique=False)
    op.create_index(op.f('ix_project_address'), 'project', ['address'], unique=False)
    op.create_index(op.f('ix_project_create_on'), 'project', ['create_on'], unique=False)
    op.create_index(op.f('ix_project_proname'), 'project', ['proname'], unique=False)
    op.create_index(op.f('ix_project_verify'), 'project', ['verify'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_verify'), table_name='project')
    op.drop_index(op.f('ix_project_proname'), table_name='project')
    op.drop_index(op.f('ix_project_create_on'), table_name='project')
    op.drop_index(op.f('ix_project_address'), table_name='project')
    op.drop_index(op.f('ix_application_verify'), table_name='application')
    op.drop_index(op.f('ix_application_image'), table_name='application')
    op.drop_index(op.f('ix_application_create_on'), table_name='application')
    op.drop_index(op.f('ix_application_containerId'), table_name='application')
    op.drop_index(op.f('ix_application_appname'), table_name='application')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_server_nickname'), table_name='server')
    op.drop_index(op.f('ix_server_create_on'), table_name='server')
    op.drop_index(op.f('ix_server_Ip'), table_name='server')
    op.drop_table('server')
    op.drop_index(op.f('ix_role_default'), table_name='role')
    op.drop_table('role')
    ### end Alembic commands ###
