"""empty message

Revision ID: 7e000734c8ba
Revises: 47809939c22e
Create Date: 2016-06-20 13:37:53.942290

"""

# revision identifiers, used by Alembic.
revision = '7e000734c8ba'
down_revision = '47809939c22e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gitlab_token', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gitlab_token')
    ### end Alembic commands ###
