"""empty message

Revision ID: 903513a1520a
Revises: 2a4be25463ec
Create Date: 2016-06-12 11:16:43.907335

"""

# revision identifiers, used by Alembic.
revision = '903513a1520a'
down_revision = '2a4be25463ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=256), nullable=False),
    sa.Column('Ip', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server')
    ### end Alembic commands ###
