"""empty message

Revision ID: 904bdb9d1600
Revises: 3b59ce42c47b
Create Date: 2016-06-27 14:35:28.715324

"""

# revision identifiers, used by Alembic.
revision = '904bdb9d1600'
down_revision = '3b59ce42c47b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('create_on', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True))
    op.create_index(op.f('ix_application_create_on'), 'application', ['create_on'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_create_on'), table_name='application')
    op.drop_column('application', 'create_on')
    ### end Alembic commands ###
