"""empty message

Revision ID: 9f9dff127b37
Revises: 904bdb9d1600
Create Date: 2016-06-27 19:09:37.573593

"""

# revision identifiers, used by Alembic.
revision = '9f9dff127b37'
down_revision = '904bdb9d1600'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('containerId', sa.String(length=256), nullable=True))
    op.add_column('application', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'application', 'project', ['project_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_column('application', 'project_id')
    op.drop_column('application', 'containerId')
    ### end Alembic commands ###
