"""empty message

Revision ID: b5a8040dd658
Revises: 903513a1520a
Create Date: 2016-06-12 14:14:46.281633

"""

# revision identifiers, used by Alembic.
revision = 'b5a8040dd658'
down_revision = '903513a1520a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('create_on', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True))
    op.create_index(op.f('ix_server_Ip'), 'server', ['Ip'], unique=False)
    op.create_index(op.f('ix_server_create_on'), 'server', ['create_on'], unique=False)
    op.create_index(op.f('ix_server_nickname'), 'server', ['nickname'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_nickname'), table_name='server')
    op.drop_index(op.f('ix_server_create_on'), table_name='server')
    op.drop_index(op.f('ix_server_Ip'), table_name='server')
    op.drop_column('server', 'create_on')
    ### end Alembic commands ###
