"""empty message

Revision ID: dd0576e9b458
Revises: 7e000734c8ba
Create Date: 2016-06-21 11:14:55.999742

"""

# revision identifiers, used by Alembic.
revision = 'dd0576e9b458'
down_revision = '7e000734c8ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appname', sa.String(length=256), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('create_on', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_address'), 'application', ['address'], unique=False)
    op.create_index(op.f('ix_application_appname'), 'application', ['appname'], unique=False)
    op.create_index(op.f('ix_application_create_on'), 'application', ['create_on'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_create_on'), table_name='application')
    op.drop_index(op.f('ix_application_appname'), table_name='application')
    op.drop_index(op.f('ix_application_address'), table_name='application')
    op.drop_table('application')
    ### end Alembic commands ###
