"""empty message

Revision ID: f400973784d6
Revises: dd0576e9b458
Create Date: 2016-06-21 16:54:36.269989

"""

# revision identifiers, used by Alembic.
revision = 'f400973784d6'
down_revision = 'dd0576e9b458'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proname', sa.String(length=256), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('create_on', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_address'), 'project', ['address'], unique=False)
    op.create_index(op.f('ix_project_create_on'), 'project', ['create_on'], unique=False)
    op.create_index(op.f('ix_project_proname'), 'project', ['proname'], unique=False)
    op.drop_table('application')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('appname', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('create_on', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(op.f('ix_project_proname'), table_name='project')
    op.drop_index(op.f('ix_project_create_on'), table_name='project')
    op.drop_index(op.f('ix_project_address'), table_name='project')
    op.drop_table('project')
    ### end Alembic commands ###
